nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - ~/web:/web

php:
  build: ./php
  ports:
    - "8000:8000"
  links:
    - "mysql"
    - "redis"
    - "memcached"
  volumes:
    - ~/web:/web
  environment:
    REDIS_PORT: 6379
    MEMCACHED_PORT: 11211 
mysql:
  build: ./mysql
  ports:
    - "10.10.48.190:3306:3306"
  volumes:
    - ~/web/data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: mzg168.2016

redis:
  build: ./redis
  ports:
    - "10.10.48.190:6379:6379"

memcached:
  build: ./memcached
  ports:
    - "10.10.48.190:11211:11211" 
